// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// composite_video //
// --------------- //

#define composite_video_wrap_target 0
#define composite_video_wrap 0

static const uint16_t composite_video_program_instructions[] = {
            //     .wrap_target
    0x6008, //  0: out    pins, 8                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program composite_video_program = {
    .instructions = composite_video_program_instructions,
    .length = 1,
    .origin = -1,
};

static inline pio_sm_config composite_video_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + composite_video_wrap_target, offset + composite_video_wrap);
    return c;
}

static inline void composite_video_program_init(PIO pio, uint sm, uint offset, uint pin_base, uint pin_count, float freq) {
    // Set up pins for use with PIO.
    for(uint i = pin_base; i < pin_base + pin_count; i++) {
        pio_gpio_init(pio, i);
    }
    // Set the pin direction to output (true) for multiple consecutive pins.
    pio_sm_set_consecutive_pindirs(pio, sm, pin_base, pin_count, true);
    pio_sm_config cfg = composite_video_program_get_default_config(offset);
    sm_config_set_out_pins(&cfg, pin_base, pin_count);
    sm_config_set_out_shift(&cfg,
        false,  // shift_right
        true,   // autopull
        8       // pull_threshold
    );
    // We're only using TX FIFO, so double the depth by joining RX FIFO.
    sm_config_set_fifo_join(&cfg, PIO_FIFO_JOIN_TX);
    float div = clock_get_hz(clk_sys) / freq;
    sm_config_set_clkdiv(&cfg, div);
    pio_sm_init(pio, sm, offset, &cfg);
    pio_sm_set_enabled(pio, sm, true);
}

#endif
